<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.example.data.repository.ResumeDataRepositoryTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2019-05-25T03:37:50" hostname="MX-IT01497" time="0.621">
  <properties/>
  <testcase name="testGetInformationSuccessful" classname="com.example.data.repository.ResumeDataRepositoryTest" time="0.611"/>
  <testcase name="testGetResumeFromFallbackCache" classname="com.example.data.repository.ResumeDataRepositoryTest" time="0.006"/>
  <testcase name="testGetInformationUnexpectedException" classname="com.example.data.repository.ResumeDataRepositoryTest" time="0.002"/>
  <testcase name="testGetInformationTimeoutError" classname="com.example.data.repository.ResumeDataRepositoryTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
